theme: jekyll-theme-hacker
## Project Proposal

### Introduction/Background

This is where we can put our introduction/background.

### Problem Definition
This is where we can put our problem definition

### Methods
This is where we can put our methods

### Potential Results
This is where we can put our potential results.

### References
This is where we can put our references.

### Timeline
This is where we can put our timeline.
